# Generated by Django 6.0.2 on 2026-03-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To-do'), ('IN_PROGRESS', 'In-progress'), ('DONE', 'Done')], default='TO_DO', max_length=11),
        ),
    ]
