# Generated by Django 6.0.2 on 2026-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("TODO", "ToDo"), ("IP", "In Progress"), ("DONE", "Done")],
                null=True,
            ),
        ),
    ]
