# Generated by Django 6.0.2 on 2026-03-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_status_alter_usersettings_default_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='default_page',
        ),
        migrations.AddField(
            model_name='tag',
            name='task_tags',
            field=models.ManyToManyField(to='core.task'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_board',
            field=models.CharField(choices=[('AGENDA', 'Agenda'), ('CALENDAR', 'Calendar'), ('KANBAN', 'Kanban'), ('PROJECT', 'Project')], default='CALENDAR', max_length=8),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=5),
        ),
    ]
