# Generated by Django 6.0.2 on 2026-03-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersettings'),
        ('core', '0005_rename_parent_task_id_task_parent_task'),
    ]

    operations = [
    ]
