# Generated by Django 6.0.2 on 2026-03-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260306_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='user_id',
            new_name='user',
        ),
    ]
