# Generated by Django 6.0.2 on 2026-03-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usersettings_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User settings', 'verbose_name_plural': 'User settings'},
        ),
    ]
